### ISSUE TITLE
Package not updated

### ISSUE THREAD

**Issue by TheJare** [conan-community/conan-zlib#23]
I'm not sure where's the right place to file this issue, but the version of this package in bintray (conan-transit) fails to build for me. Win10Pro x64, VS 2017 15.5, CMake 3.10, conan 0.29.2 installed via pip on python 2.7.14.

```
zlib/1.2.11@lasote/stable: WARN: Build folder d:\Soft\conan-home\data\zlib\1.2.11\lasote\stable\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
ERROR: zlib/1.2.11@lasote/stable: Error in build() method, line 59
        cmake = CMake(self.settings)
        ConanException: First argument of CMake() has to be ConanFile. Use CMake(self)
```

I see that line was fixed in https://github.com/lasote/conan-zlib/commit/2a1965eb6070e92a6c2c4bd59bae4ff053391815#diff-2b1d42f71f22b7ea0412d7602dec166fL53 but it does not seem to be in the released package. How can I use this package?

**Comment by kaidokert** [comment]
I just ran into the same issue and reported at conan-io/conan/issues/2136

**Comment by lasote** [comment]
Try to use zlib/1.2.11@conan/stable from conan-center: https://bintray.com/conan-community/conan/zlib%3Aconan

@kaidokert about the related issue you pointed, let us review the docs and get it right.

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#59
