### ISSUE TITLE
Add more compilers to CI

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [conan-community/conan-zlib#24]
Hello,
Can you add more compilers to conan-zlib package? If we will have more prebuilt packages for more compilers, Binccrafters team will be able to add more compilers for packages, which are based on conan-zlib.

I remind you, that you have nice docker hub with ready to use images: https://hub.docker.com/u/lasote/

**Comment by lasote** [comment]
Hi! I updated some of them some days ago, could you check if you still need some more configuration?

**Comment by Croydon** [comment]
I'm pretty sure this can be closed now.
