### ISSUE TITLE
package_info for static windows

### ISSUE THREAD

**Issue by Brunni** [conan-community/conan-zlib#26]
Hi all,

shouldn't the package_info for static windows library not be "zlibstatic.lib" ?

Regards
Michael

**Comment by lasote** [comment]
Hi @Brunni!

Do you have an error or it is just an observation about naming conventions?
I'm just packing the library that the zlib build system generates, if it should have a different name maybe we should talk with the zlib author.

Thanks!

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#58
