### ISSUE TITLE
Unrecognized relocation issue under CentOS 6/7 and Debian 8 

### ISSUE THREAD

**Issue by rdeterre** [conan-community/conan-zlib#28]
Hi,

Building a project that depends on `boost/1.66.0@conan/stable` fails on various Linux machines (CentOS 6, CentOS 7 and Debian 8) with an "unrecognized relocation (0x2a) in section `.text'" error.

The problem appears when using the default generated profile on the build machines, but also when `compiler.libcxx` is set to `libstdc++11` instead of it's standard value of `libstdc++`.

I tried forcing `zlib:shared` to `True`, but this does not solve the problem. Strangely, the error still shows  ".../libz.a(deflate.o): unrecognized relocation (0x2a) in section `.text'", leading me to think that the shared option maybe doesn't work as expected.

The problem is solved on all machines by forcing a rebuild of zlib.

**Comment by lasote** [comment]
Hi, thanks for reporting. Could you paste here the profile applied? I need to see the `gcc` version and the other settings applied.

**Comment by rdeterre** [comment]
Sure. I use the profile that is auto-generated by conan on all machines. Here it is on Debian 8:

```
[build_requires]
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=4.9
compiler.libcxx=libstdc++
build_type=Release
[options]
[env]
```

**Comment by JohnboyJovi** [comment]
I had the same problem, with CentOs and gcc 5.3. This I could solve by not using the binary package but forcing a rebuild with ``--build zlib`` 

So I guess something is wrong with package ``zlib/1.2.11@conan/stable:52bcde7d26fabb9754f2f3b850001579b1098686``

The binary package for gcc 6.3 however works.

**Comment by lasote** [comment]
Thanks to both for answering, I'm taking a look.

**Comment by lasote** [comment]
By the way, the usage of zlib shared is harcoded in the boost recipe `configure()` method, so it ignores the override:

```
    def configure(self):
        if self.zip_bzip2_requires_needed:
            self.requires("bzip2/1.0.6@conan/stable")
            self.options["bzip2"].shared = False
            
            self.requires("zlib/1.2.11@conan/stable")
            self.options["zlib"].shared = False
```

**Comment by lasote** [comment]
Hi all! Could you verify if the errors are gone now? It is needed to update the binary packages from bzip2 and zlib, so use `--update` in the `conan install` command.
Working fine on my Debian 9.

**Comment by JohnboyJovi** [comment]
Yes, works for me. Thank you!

**Comment by rdeterre** [comment]
All good here. Thanks!
