### ISSUE TITLE
Unable to build zlib 1.2.11

### ISSUE THREAD

**Issue by macdew** [conan-community/conan-zlib#29]
I've tried to run this script locally, but it won't run for me (Windows 10/msvc 2017).

The downloaded zlib source archive unzips into a subfolder called zlib-1.2.11.  CMake then tries to run in the (parent) build folder, and therefore can't find CMakeLists.txt.

I'm also concerned by the line: cmake.configure(build_dir=".")
build_dir is not a valid parameter to configure, it should be build_folder?   I tried constructing and passing a correct source_folder path to the configure command, but that did not fix the issue with the source being extracted into a subfolder.

**Comment by lasote** [comment]
Please paste here the command you typed. You can create packages from the repository with:
`conan create . user/channel`

**Comment by macdew** [comment]
I am now able to reproduce this on a second machine...  Note that we have a need to build everything off-line, so I cannot use the default remote source.

My command:

conan create . demo/testing
where conanfile.py is the one from this project.

The output from the command is:

D:\source\zlib>conan create . demo/testing
zlib/1.2.11@demo/testing: Exporting package recipe
zlib/1.2.11@demo/testing: A new conanfile.py version was exported
zlib/1.2.11@demo/testing: Folder: C:\Users\macdew\.conan\data\zlib\1.2.11\demo\testing\export
zlib/1.2.11@demo/testing: Installing package
Requirements
    zlib/1.2.11@demo/testing from local cache
Packages
    zlib/1.2.11@demo/testing:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7

zlib/1.2.11@demo/testing: WARN: Forced build from source
zlib/1.2.11@demo/testing: Building your package in C:\Users\macdew\.conan\data\zlib\1.2.11\demo\testing\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
zlib/1.2.11@demo/testing: Configuring sources in C:\Users\macdew\.conan\data\zlib\1.2.11\demo\testing\source
[==================================================] 593.5KB/593.5KB
zlib/1.2.11@demo/testing: Copying sources to build folder
zlib/1.2.11@demo/testing: Generator cmake created conanbuildinfo.cmake
zlib/1.2.11@demo/testing: Calling build()
CMake Error: The source directory "C:/Users/macdew/.conan/data/zlib/1.2.11/demo/testing/build/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
zlib/1.2.11@demo/testing:
zlib/1.2.11@demo/testing: ERROR: Package '6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7' build failed
zlib/1.2.11@demo/testing: WARN: Build folder C:\Users\macdew\.conan\data\zlib\1.2.11\demo\testing\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
ERROR: zlib/1.2.11@demo/testing: Error in build() method, line 55
        cmake.configure(build_dir=".")
        ConanException: Error 1 while executing cd . && cmake -G "Visual Studio 15 2017 Win64" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="15" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\macdew\.conan\data\zlib\1.2.11\demo\testing\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7" -DCONAN_CXX_FLAGS="/MP16" -DCONAN_C_FLAGS="/MP16" -Wno-dev C:\Users\macdew\.conan\data\zlib\1.2.11\demo\testing\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7

The cmake command shown here doesn't make sense to me.  Inspecting the build folder shows that the source is in a zlib-1.2.11 subfolder, and this isn't being passed to CMake?

**Comment by macdew** [comment]
Ah, my bad  -  it was my first Conan package.  I now understand that I needed the cmake file from this repository.  Conan will invoke this file first, which then includes the zlib standard one.  Everything now works as expected, I shall close this issue!
