### ISSUE TITLE
Android build on Win10

### ISSUE THREAD

**Issue by khindemit** [conan-community/conan-zlib#35]
Hello!
I am trying to follow the tutorial from conan: https://docs.conan.io/en/latest/integrations/android_studio.html

The libpng library have zlib as a dependency. When conan trying to download and build the zlib library the following error occurs:

ERROR: zlib/1.2.11@conan/stable: Error in source() method, line 30
  	self.run("chmod +x ./%s/configure" % self.ZIP_FOLDER_NAME)
  	ConanException: Error 1 while executing chmod +x ./zlib-1.2.11/configure
   err> "chmod" ­Ґ пў«пҐвбп ў­гваҐ­­Ґ© Ё«Ё ў­Ґи­Ґ©
  Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.

Strange letters due to the fact that my Windows is in Russian, here is translated text:
"chmod" is not internal or external
command, executable program or batch file.

Here is the build log:
[conan_build_log.txt](https://github.com/conan-community/conan-zlib/files/1998824/conan_build_log.txt)

Here is conan profile:
[android_21_arm_clang.txt](https://github.com/conan-community/conan-zlib/files/1998827/android_21_arm_clang.txt)

Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by lasote** [comment]
Hi, sorry for the delay, I opened a PR, when the CI ends (very busy today) we can merge it to solve this issue. Please, ping me if I do not respond tomorrow.
Thanks

**Comment by khindemit** [comment]
@lasote Ping!

**Comment by lasote** [comment]
Merged!
