### ISSUE TITLE
cross compiling (mingw64 on linux64) cannot find static library

### ISSUE THREAD

**Issue by pro-spero** [conan-community/conan-zlib#38]
Using a x86_64-w64-mingw32-gcc toolchain on Linux64 compiles the binaries, but fails in the package() call.

RROR: zlib/1.2.11@conan/stable: Error in package() method, line 103
        os.rename(current_lib, os.path.join(lib_path, "libzlib.a"))
        FileNotFoundError: [Errno 2] No such file or directory: '/home/philipp/.conan/data/zlib/1.2.11/conan/stable/package/42951bc9791ea38175dc6d678bd77956f88c4796/lib/libzlibstatic.a' -> '/home/philipp/.conan/data/zlib/1.2.11/conan/stable/package/42951bc9791ea38175dc6d678bd77956f88c4796/lib/libzlib.a'

No such library is built. Instead, library resulting from the build is named 'libz.a'.

**Comment by lasote** [comment]
Hi, I'm testing the fix here: 

https://travis-ci.org/conan-community/conan-zlib/builds/399886763
https://ci.appveyor.com/project/lasote/conan-zlib-7h7rb

I will merge it to master after If it ends correctly.

**Comment by lasote** [comment]
Please, try it now (if you have already installed in your local cache make sure to use `--update` in the install). Let me know if you have any problem.

**Comment by pro-spero** [comment]
It now builds successfully.
Thank you very much!
