### ISSUE TITLE
Upload latest version to bintray

### ISSUE THREAD

**Issue by GeorgeScrivener** [conan-community/conan-zlib#45]
I'm having issues on gcc 7.3 that is fixed by [1eb92e0](https://github.com/conan-community/conan-zlib/commit/1eb92e03a56db95268cbeccce96720750d7bad1c#diff-2b1d42f71f22b7ea0412d7602dec166f).

Please could you push the latest version up to bintray?
Thanks

**Comment by lasote** [comment]
It should be in bintray... do you think it is not? This job worked ok:

https://travis-ci.org/conan-community/conan-zlib/jobs/409727488

**Comment by GeorgeScrivener** [comment]
I might have made a mistake but looking [here](https://bintray.com/conan-community/conan/zlib%3Aconan/1.2.11%3Astable) says `Updated in Jul 03, 2018`.
I'm using `zlib/1.2.11@conan/stable` in my recipes.  Do I need to use a different channel?

**Comment by lasote** [comment]
You are right, surprisingly the uploaded recipe is not the latest. Let me relaunch it.

**Comment by GeorgeScrivener** [comment]
Thanks

**Comment by lasote** [comment]
Launched: https://travis-ci.org/conan-community/conan-zlib/builds/422562626
Let me know once it ends if everything works ok.

**Comment by GeorgeScrivener** [comment]
Appears to have the same issue.
Looking at the logs [here](https://travis-ci.org/conan-community/conan-zlib/jobs/422562632) it says:

    1053 Uploading zlib/1.2.11@conan/stable to remote 'upload_repo'
    1054 Compressing recipe sources...                                         Recipe is up to date, upload skipped
    1055 Uploading package 1/1: a07bda1288c1de2210aee39b658038998f6fb2e8

**Comment by lasote** [comment]
That is because other job uploaded the recipe already. I checked in Bintray and now the conanfile.py has the latest changes.

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#55
