### ISSUE TITLE
Some private header files are exposed

### ISSUE THREAD

**Issue by liberforce** [conan-community/conan-zlib#46]
This is similar to #13.

1.2.11 exposes those files in `include/`
```
crc32.h
inffixed.h
trees.h
inftrees.h
zutil.h
deflate.h
inffast.h
gzguts.h
zlib.h
gzlog.h
inflate.h
zconf.h
```

But most of these files are private API and should not be exposed. Most of them contain a warning such as this one:

```
    /* WARNING: this file should *not* be used by applications.
       It is part of the implementation of this library and is
       subject to change. Applications should only use zlib.h.
     */
```

Debian only ships `zlib.h` and `zconf.h`, so that is most probably enough.

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#54
