### ISSUE TITLE
pkg-config file has hardcoded prefix

### ISSUE THREAD

**Issue by liberforce** [conan-community/conan-zlib#48]
```
$ conan install -o '*:shared=True' -o '*:fPic=True' zlib/1.2.11@conan/stable
...
$ head -n 1 $HOME/.conan/data/zlib/1.2.11/conan/stable/package/a79ecbb5554da8510d2c9d7856daeb24de6be0d9/zlib.pc 
prefix=/home/conan/.conan/data/zlib/1.2.11/conan/stable/package/a79ecbb5554da8510d2c9d7856daeb24de6be0d9
```

My `$HOME` is not `/home/conan`, that is the home where the package was built. Unless I'm overlooking something, I think the pkg-config can't contain an hardcoded installation location as it is meaningful only on the machine where it was built, not where it is installed. So that looks broken to me.

It could use a path relative to a variable containing the equivalent of `CONAN_HOME`, and passing that variable to pkg-config on calls. Maybe there's a better solution?

**Comment by liberforce** [comment]
Location of the file looks wrong too, it should IMHO be in `share/pkgconfig`.

**Comment by SSE4** [comment]
yes, I've also noticed location is wrong, I'll change it to use the standard location
for hard-coded prefix, please try to use `tools.replace_prefix_in_pc_file`
(see for the complete example https://github.com/bincrafters/conan-ffmpeg/blob/stable/4.0/conanfile.py#L213)

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#53
