### ISSUE TITLE
Failed to download from conan

### ISSUE THREAD

**Issue by Shin-nn** [conan-community/conan-zlib#52]
From today I am unable to download and build zlib:
> $ conan  install zlib/1.2.11@conan/stable
> zlib/1.2.11@conan/stable: Retrieving from predefined remote 'conan-center'
> zlib/1.2.11@conan/stable: Trying with 'conan-center'...
> ERROR: Failed requirement 'zlib/1.2.11@conan/stable' from 'PROJECT'
> ERROR: {"message":"Oops. Looks like you've reached a dark spot."}. [Remote: conan-center]

I do not know if this issues is related to bintray or your package.
Can you help me?

Thank you!

**Comment by notskm** [comment]
I just ran into the same problem. Simply searching for zlib errors out, too.
```
$ conan search zlib -r=conan-center
ERROR: {"message":"Oops. Looks like you've reached a dark spot."}. [Remote: conan-center]
```

**Comment by AnotherMuggle** [comment]
This is causing me a problem too. I noticed the package has an updated date of today but I don't know how to troubleshoot.

**Comment by gagelarsen** [comment]
I'm having the same issue. Any word on a fix yet?

**Comment by AnotherMuggle** [comment]
> I'm having the same issue. Any word on a fix yet?

I just retried and it seems to be working again!?

**Comment by gagelarsen** [comment]
It is working now
